"""Initial migration

Revision ID: 7a49316b4b04
Revises: 2a25798e298c
Create Date: 2026-02-11 20:05:40.105412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a49316b4b04'
down_revision: Union[str, Sequence[str], None] = '2a25798e298c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create market_snapshots table
    op.create_table('market_snapshots',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('symbol', sa.String, index=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), index=True),
        sa.Column('spot_price', sa.Float),
        sa.Column('vwap', sa.Float, nullable=True),
        sa.Column('change', sa.Float, nullable=True),
        sa.Column('change_percent', sa.Float, nullable=True),
        sa.Column('volume', sa.Integer, nullable=True),
        sa.Column('market_status', sa.String, nullable=True),
        
        # Add derived directional features
        sa.Column('rsi', sa.Float, nullable=True),
        sa.Column('momentum_score', sa.Float, nullable=True),
        sa.Column('regime', sa.String, nullable=True)
    )
    
    # Create option_chain_snapshots table
    op.create_table('option_chain_snapshots',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('market_snapshot_id', sa.Integer, sa.ForeignKey('market_snapshots.id')),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), index=True),
        sa.Column('strike', sa.Float, index=True),
        sa.Column('option_type', sa.String),  # CE or PE
        sa.Column('expiry', sa.String),
        
        # Options Greeks and metrics
        sa.Column('oi', sa.Integer),
        sa.Column('oi_change', sa.Integer, nullable=True),
        sa.Column('ltp', sa.Float),
        sa.Column('iv', sa.Float),
        sa.Column('volume', sa.Integer),
        sa.Column('theta', sa.Float, nullable=True),
        sa.Column('delta', sa.Float, nullable=True),
        sa.Column('gamma', sa.Float, nullable=True),
        sa.Column('vega', sa.Float, nullable=True)
    )
    
    # Create predictions table
    op.create_table('predictions',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), index=True),
        sa.Column('symbol', sa.String, index=True),
        
        # ML prediction outputs
        sa.Column('bullish_probability', sa.Float),
        sa.Column('volatility_probability', sa.Float),
        sa.Column('confidence_score', sa.Float),
        sa.Column('regime', sa.String),
        
        # Performance tracking
        sa.Column('actual_move_30m', sa.Float, nullable=True),
        sa.Column('accuracy_score', sa.Float, nullable=True),
        sa.Column('model_version', sa.String)
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
