# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MarketDataFeed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MarketDataFeed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MarketDataFeed.proto\x12\x15\x63om.upstox.marketdata\"\x98\x01\n\x0c\x46\x65\x65\x64Response\x12=\n\x05\x66\x65\x65\x64s\x18\x01 \x03(\x0b\x32..com.upstox.marketdata.FeedResponse.FeedsEntry\x1aI\n\nFeedsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.com.upstox.marketdata.Feed:\x02\x38\x01\"-\n\x04\x46\x65\x65\x64\x12%\n\x02\x66\x66\x18\x01 \x01(\x0b\x32\x19.com.upstox.marketdata.FF\"5\n\x02\x46\x46\x12/\n\x07indexFF\x18\x01 \x01(\x0b\x32\x1e.com.upstox.marketdata.IndexFF\"4\n\x07IndexFF\x12)\n\x04ltpc\x18\x01 \x01(\x0b\x32\x1b.com.upstox.marketdata.LTPC\"\x13\n\x04LTPC\x12\x0b\n\x03ltp\x18\x01 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MarketDataFeed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDRESPONSE_FEEDSENTRY']._loaded_options = None
  _globals['_FEEDRESPONSE_FEEDSENTRY']._serialized_options = b'8\001'
  _globals['_FEEDRESPONSE']._serialized_start=48
  _globals['_FEEDRESPONSE']._serialized_end=200
  _globals['_FEEDRESPONSE_FEEDSENTRY']._serialized_start=127
  _globals['_FEEDRESPONSE_FEEDSENTRY']._serialized_end=200
  _globals['_FEED']._serialized_start=202
  _globals['_FEED']._serialized_end=247
  _globals['_FF']._serialized_start=249
  _globals['_FF']._serialized_end=302
  _globals['_INDEXFF']._serialized_start=304
  _globals['_INDEXFF']._serialized_end=356
  _globals['_LTPC']._serialized_start=358
  _globals['_LTPC']._serialized_end=377
# @@protoc_insertion_point(module_scope)
