# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MarketDataFeedV3.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'MarketDataFeedV3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16MarketDataFeedV3.proto\x12\nmarketdata\"9\n\x04LTPC\x12\x0b\n\x03ltp\x18\x01 \x01(\x01\x12\x0b\n\x03ltt\x18\x02 \x01(\x01\x12\x0b\n\x03ltq\x18\x03 \x01(\x01\x12\n\n\x02\x63p\x18\x04 \x01(\x01\"N\n\x04\x46\x65\x65\x64\x12 \n\x04ltpc\x18\x01 \x01(\x0b\x32\x10.marketdata.LTPCH\x00\x12\x1c\n\x02\x66\x66\x18\x02 \x01(\x0b\x32\x0e.marketdata.FFH\x00\x42\x06\n\x04\x64\x61ta\"^\n\x02\x46\x46\x12&\n\x07indexFF\x18\x01 \x01(\x0b\x32\x13.marketdata.IndexFFH\x00\x12(\n\x08marketFF\x18\x02 \x01(\x0b\x32\x14.marketdata.MarketFFH\x00\x42\x06\n\x04\x64\x61ta\")\n\x07IndexFF\x12\x1e\n\x04ltpc\x18\x01 \x01(\x0b\x32\x10.marketdata.LTPC\"*\n\x08MarketFF\x12\x1e\n\x04ltpc\x18\x01 \x01(\x0b\x32\x10.marketdata.LTPC\":\n\nFeedsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.marketdata.Feed\"U\n\x0c\x46\x65\x65\x64Response\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.marketdata.Type\x12%\n\x05\x66\x65\x65\x64s\x18\x02 \x03(\x0b\x32\x16.marketdata.FeedsEntry*8\n\x04Type\x12\x10\n\x0cinitial_feed\x10\x00\x12\r\n\tlive_feed\x10\x01\x12\x0f\n\x0bmarket_info\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MarketDataFeedV3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TYPE']._serialized_start=507
  _globals['_TYPE']._serialized_end=563
  _globals['_LTPC']._serialized_start=38
  _globals['_LTPC']._serialized_end=95
  _globals['_FEED']._serialized_start=97
  _globals['_FEED']._serialized_end=175
  _globals['_FF']._serialized_start=177
  _globals['_FF']._serialized_end=271
  _globals['_INDEXFF']._serialized_start=273
  _globals['_INDEXFF']._serialized_end=314
  _globals['_MARKETFF']._serialized_start=316
  _globals['_MARKETFF']._serialized_end=358
  _globals['_FEEDSENTRY']._serialized_start=360
  _globals['_FEEDSENTRY']._serialized_end=418
  _globals['_FEEDRESPONSE']._serialized_start=420
  _globals['_FEEDRESPONSE']._serialized_end=505
# @@protoc_insertion_point(module_scope)
